version: '3.4'

networks:
  tvscanner_backend:
  tvscanner_frontend:

services:
  tvscannerweb:
    image: ${DOCKER_REGISTRY-}tvscannerweb
    build:
      context: .
      dockerfile: Dockerfile.Web
      args:
        - API_URL=http://localhost:15005/
    ports:
      - 15007:80
    depends_on:
      - tvscannerapi
    networks:
    - tvscanner_frontend
  tvscannerapi:
    image: ${DOCKER_REGISTRY-}tvscannerapi
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.API
    ports:
    - 15005:8080
    - 15006:8081
    volumes: # copy over user secrets from your development machine
     - ~/.aspnet/https:/https:ro
     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - tvscannerdb
    networks:
    - tvscanner_backend
    - tvscanner_frontend
  tvscannerdb:
    image: ${DOCKER_REGISTRY-}tvscannerdb
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.Database
      args:
         - DB_PASSWORD=Password123
    ports:
      - 15008:5432
    networks:
      - tvscanner_backend