version: '3.4'

networks:
  tvscanner_backend:
  tvscanner_frontend:

services:
  tvscannerweb:
    image: ghcr.io/badhax/tradingviewscanner/tvscannerweb:latest
    ports:
      - 15007:80
    depends_on:
      - tvscannerapi
    networks:
    - tvscanner_frontend
  tvscannerapi:
    image: ghcr.io/badhax/tradingviewscanner/tvscannerapi:latest
    restart: on-failure
    ports:
    - 15005:8080
    - 15006:8081
    depends_on:
      - tvscannerdb
    networks:
    - tvscanner_backend
    - tvscanner_frontend
  tvscannerdb:
    image: ghcr.io/badhax/tradingviewscanner/tvscannerdb:latest
    restart: on-failure
    networks:
      - tvscanner_backend