version: '3.4'

networks:
  tvscanner_backend:
  tvscanner_frontend:

services:
  tvscannerweb:
    image: ${DOCKER_REGISTRY-}tvscannerweb
    build:
      context: .
      dockerfile: Dockerfile.Web
    ports:
      - 15007:80
    environment:
      - API_URL=https://localhost:15006
    depends_on:
      - tvscannerapi
    networks:
    - tvscanner_frontend
  tvscannerapi:
    image: ${DOCKER_REGISTRY-}tvscannerapi
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.API
    ports:
    - 15005:8080
    - 15006:8081
    environment: # Development environment variables
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TVScannerContext=Host=tvscanner.db;Port=5432;Database=TVScanner;Username=postgres;password=Password123;
      - Logging__LogLevel__Default=Information
    depends_on:
      - tvscannerdb
    networks:
    - tvscanner_backend
    - tvscanner_frontend
  tvscannerdb:
    image: ${DOCKER_REGISTRY-}tvscannerdb
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.Database
    ports:
      - 15008:5432
    environment:
      - DB_PASSWORD=Password123
    networks:
      - tvscanner_backend