name: Docker Image CI

on:
  workflow_run:
    workflows: [ .Net ]
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Publish Web Image
      uses: matootie/github-docker@v3.1.0
      id: publish-webapp
      with:
        accessToken: ${{ github.token }}
        imageName: ${{ secrets.WEBAPP_NAME }}
        contextName: Dockerfile.Web
        buildArgs: |
            API_URL=${{ secrets.API_URL }}
        
    - name: Publish API Image
      uses: matootie/github-docker@v3.1.0
      id: publish-api
      with:
        accessToken: ${{ github.token }}
        imageName: ${{ secrets.API_NAME }}
        contextName: Dockerfile.API
            
    # - name: Publish Db Image
    #   uses: matootie/github-docker@v3.1.0
    #   id: publish-db
    #   with:
    #     accessToken: ${{ github.token }}
    #     imageName: ${{ secrets.DB_NAME }}
    #     contextName: Dockerfile.Database
    #     buildArgs: |
    #         DB_PASSWORD= ${{ secrets.DB_PASSWORD }}

    # - name: Deploy to swarm
    #   uses: sagebind/docker-swarm-deploy-action@v2
    #   with:
    #     remote_host: ${{ secrets.DOCKER_SSH_HOST }}
    #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
    #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
    #     args: stack deploy --with-registry-auth --compose-file docker-compose.prod.yaml tvscanner
