# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TVScanner.sln
    - name: Build
      run: dotnet build TVScanner.sln --no-restore
    - name: Test
      run: dotnet test TVScanner.sln --no-build --verbosity normal

    - name: Publish Web Image
      uses: matootie/github-docker@v3.1.0
      id: publish-webapp
      with:
        accessToken: ${{ github.token }}
        imageName: ${{ secrets.WEBAPP_NAME }}
        contextName: Docker.Web
        
    - name: Publish API Image
      uses: matootie/github-docker@v3.1.0
      id: publish-api
      with:
        accessToken: ${{ github.token }}
        imageName: ${{ secrets.API_NAME }}
        contextName: Docker.API
        
    - name: Print Web Image URL
      run: |
        echo ${{ steps.publish-webapp.outputs.imageURL }}
        echo ${{ steps.publish-api.outputs.imageURL }}